# Generated by Django 5.1.7 on 2025-04-06 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingaddress',
            old_name='city',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='shoppingaddress',
            name='state',
        ),
    ]
