# Generated by Django 5.1.7 on 2025-04-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
