# Generated by Django 5.1.7 on 2025-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media1',
            field=models.ImageField(blank=True, null=True, upload_to='product/media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='media2',
            field=models.ImageField(blank=True, null=True, upload_to='product/media/'),
        ),
        migrations.AddField(
            model_name='product',
            name='media3',
            field=models.ImageField(blank=True, null=True, upload_to='product/media/'),
        ),
    ]
