# Generated by Django 5.1.7 on 2025-04-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_media1_product_media2_product_media3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media1',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
